#\u914D\u7F6E\u7528\u6237\u540D\u8DDF\u5BC6\u7801\u7B49\u9700\u8981\u5C5E\u6027
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
